---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app-demo
  namespace: production
spec:
  filterTags:
    extract: $timestamp
    pattern: ^RELEASE\.(?P<timestamp>.*)Z$
  imageRepositoryRef:
    name: app-demo
  policy:
    alphabetical:
      order: asc

